# Generated by Django 2.2.12 on 2020-07-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(editable=False, max_length=15)),
                ('balance', models.FloatField(default=0)),
                ('owner', models.CharField(editable=False, max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
