# Generated by Django 2.2.12 on 2020-07-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAccount', models.CharField(editable=False, max_length=15)),
                ('toAccount', models.CharField(editable=False, max_length=15)),
                ('amount', models.FloatField(default=0)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
